#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';
use lib $ENV{OPENSHIFT_REPO_DIR} . '/diy/lib';

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Diy');
